server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuarios
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/usuario/**
        - id: productos
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/producto/**
        - id: pedidos
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/pedido/**